from manim import *
from grow_shrink import GrowShrink
from helper_funcs import *
from diamond_square import default_biome_htc
from diamond_animation import *

class CorrectRoughScene(Scene):
    def construct(self):
        self.camera.background_color = DARKER_GRAY

        grid = VGroup(*[Square(side_length=1.425) for i in range(25)])
        grid.arrange_in_grid(rows=5, cols=5, buff=0)
        grid.set_stroke(color=WHITE, width=2)
        grid.set_fill(opacity=0)
        grid.shift(LEFT * 2)
        fake_rough_hmap = [0.33, 0.0, 0.36, 0.0, -0.44, 0.0, 0.12, 0.0, -0.48, 0.0, -0.47, 0.0, 0.12, 0.0, -0.13, 0.0, 0.03, 0.0, -0.35, 0.0, -0.49, 0.0, 0.03, 0.0, 0.31]
        height_map = [
            0.1700, 0.2550, 0.3400, 0.4250, 0.5100,
            0.2800, 1.0313, 0.3313, 0.3494, 0.3138,
            0.3900, 0.3313, 0.3225, 0.3218, 0.2550,
            0.5000, 0.4069, 0.3138, 0.2942, 0.1275,
            0.6100, 0.4575, 0.3050, 0.1525, 0.0000
        ]
        hmap_difference = []

        for i in range(len(height_map)):
            hmap_difference.append(fake_rough_hmap[i] - height_map[i])

        hmap_mobjects = VGroup()
        for index, value in enumerate(height_map):
            mobject = MathTex(f"{value:.2f}", color=get_matching_color(default_biome_htc(height_map[index])), z_index=100).move_to(grid[index])
            hmap_mobjects.add(mobject)

        hmap2_mobjects = VGroup()
        for index, value in enumerate(fake_rough_hmap):
            mobject = MathTex(f"{value:.2f}", color=get_matching_color(default_biome_htc(fake_rough_hmap[index])), z_index=100).move_to(grid[index])
            hmap2_mobjects.add(mobject)

        hmap_add_mobjects = VGroup()
        for index, value in enumerate(hmap_difference):
            mobject = MathTex(f"+({value:.2f})", color=get_matching_color(default_biome_htc(height_map[index])), z_index=100).scale(0.75).next_to(hmap_mobjects[index], DOWN, buff=0.05)
            hmap_add_mobjects.add(mobject)

        randomness_tex = MathTex(r"h+rand(-r, r)").scale(1.5).to_corner(UR)
        r_tex = Tex("$r:$ \"roughness\"").next_to(randomness_tex, DOWN)
        r_val_tex = MathTex(r"r_{\text{start}} = 0.5").next_to(r_tex, DOWN)
        r_change_tex = MathTex(r"r = r * r_{\text{start}}").next_to(r_val_tex, DOWN)

        self.play(Write(grid))
        self.wait(3)
        self.play(Write(hmap_mobjects[0]), grid[0].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[0])), opacity=1))
        self.play(Write(hmap_mobjects[4]), grid[4].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[4])), opacity=1))
        self.play(Write(hmap_mobjects[20]), grid[20].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[20])), opacity=1))
        self.play(Write(hmap_mobjects[24]), grid[24].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[24])), opacity=1))
        self.play(GrowShrink(grid[12]))
        self.play(GrowShrink(grid[0], grid[4], grid[20], grid[24]))
        self.play(Write(hmap_mobjects[12]), grid[12].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[12])), opacity=1))
        self.wait(5)
        self.play(Write(randomness_tex))
        self.wait(1)
        self.play(Write(r_tex))
        self.wait(1)
        self.play(Write(r_val_tex))
        self.wait(3)
        self.play(Write(r_change_tex))
        self.wait(3)
        self.play(Write(hmap_add_mobjects[12]))
        self.wait(1)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[12], hmap_mobjects[12]), hmap2_mobjects[12]), grid[12].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[12])), opacity=1), run_time=0.5)
        self.wait(5)
        self.play(GrowShrink(grid[2], run_time=0.25))
        self.play(GrowShrink(grid[0], grid[4], run_time=0.25))
        self.play(Write(hmap_mobjects[2]), grid[2].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[2])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[2]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[2], hmap_mobjects[2]), hmap2_mobjects[2]), grid[2].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[2])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[14], run_time=0.25))
        self.play(GrowShrink(grid[4], grid[24], run_time=0.25))
        self.play(Write(hmap_mobjects[14]), grid[14].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[14])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[14]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[14], hmap_mobjects[14]), hmap2_mobjects[14]), grid[14].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[14])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[22], run_time=0.25))
        self.play(GrowShrink(grid[20], grid[24], run_time=0.25))
        self.play(Write(hmap_mobjects[22]), grid[22].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[22])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[22]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[22], hmap_mobjects[22]), hmap2_mobjects[22]), grid[22].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[22])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[10], run_time=0.25))
        self.play(GrowShrink(grid[0], grid[20], run_time=0.25))
        self.play(Write(hmap_mobjects[10]), grid[10].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[10])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[10]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[10], hmap_mobjects[10]), hmap2_mobjects[10]), grid[10].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[10])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[6], run_time=0.25))
        self.play(GrowShrink(grid[0], grid[2], grid[10], grid[12], run_time=0.25))
        self.play(Write(hmap_mobjects[6]), grid[6].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[6])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[6]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[6], hmap_mobjects[6]), hmap2_mobjects[6]), grid[6].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[6])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[16], run_time=0.25))
        self.play(GrowShrink(grid[10], grid[12], grid[20], grid[22], run_time=0.25))
        self.play(Write(hmap_mobjects[16]), grid[16].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[16])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[16]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[16], hmap_mobjects[16]), hmap2_mobjects[16]), grid[16].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[16])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[8], run_time=0.25))
        self.play(GrowShrink(grid[2], grid[4], grid[12], grid[14], run_time=0.25))
        self.play(Write(hmap_mobjects[8]), grid[8].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[8])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[8]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[8], hmap_mobjects[8]), hmap2_mobjects[8]), grid[8].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[8])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[18], run_time=0.25))
        self.play(GrowShrink(grid[12], grid[14], grid[22], grid[24], run_time=0.25))
        self.play(Write(hmap_mobjects[18]), grid[18].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[18])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[18]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[18], hmap_mobjects[18]), hmap2_mobjects[18]), grid[18].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[18])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[1], run_time=0.25))
        self.play(GrowShrink(grid[0], grid[2], run_time=0.25))
        self.play(Write(hmap_mobjects[1]), grid[1].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[1])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[1]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[1], hmap_mobjects[1]), hmap2_mobjects[1]), grid[1].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[1])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[7], run_time=0.25))
        self.play(GrowShrink(grid[2], grid[12], run_time=0.25))
        self.play(Write(hmap_mobjects[7]), grid[7].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[7])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[7]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[7], hmap_mobjects[7]), hmap2_mobjects[7]), grid[7].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[7])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[11], run_time=0.25))
        self.play(GrowShrink(grid[10], grid[12], run_time=0.25))
        self.play(Write(hmap_mobjects[11]), grid[11].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[11])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[11]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[11], hmap_mobjects[11]), hmap2_mobjects[11]), grid[11].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[11])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[5], run_time=0.25))
        self.play(GrowShrink(grid[0], grid[10], run_time=0.25))
        self.play(Write(hmap_mobjects[5]), grid[5].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[5])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[5]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[5], hmap_mobjects[5]), hmap2_mobjects[5]), grid[5].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[5])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[17], run_time=0.25))
        self.play(GrowShrink(grid[12], grid[22], run_time=0.25))
        self.play(Write(hmap_mobjects[17]), grid[17].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[17])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[17]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[17], hmap_mobjects[17]), hmap2_mobjects[17]), grid[17].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[17])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[21], run_time=0.25))
        self.play(GrowShrink(grid[20], grid[22], run_time=0.25))
        self.play(Write(hmap_mobjects[21]), grid[21].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[21])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[21]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[21], hmap_mobjects[21]), hmap2_mobjects[21]), grid[21].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[21])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[15], run_time=0.25))
        self.play(GrowShrink(grid[10], grid[20], run_time=0.25))
        self.play(Write(hmap_mobjects[15]), grid[15].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[15])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[15]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[15], hmap_mobjects[15]), hmap2_mobjects[15]), grid[15].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[15])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[3], run_time=0.25))
        self.play(GrowShrink(grid[2], grid[4], run_time=0.25))
        self.play(Write(hmap_mobjects[3]), grid[3].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[3])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[3]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[3], hmap_mobjects[3]), hmap2_mobjects[3]), grid[3].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[3])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[9], run_time=0.25))
        self.play(GrowShrink(grid[4], grid[14], run_time=0.25))
        self.play(Write(hmap_mobjects[9]), grid[9].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[9])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[9]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[9], hmap_mobjects[9]), hmap2_mobjects[9]), grid[9].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[9])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[13], run_time=0.25))
        self.play(GrowShrink(grid[8], grid[18], run_time=0.25))
        self.play(Write(hmap_mobjects[13]), grid[13].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[13])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[13]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[13], hmap_mobjects[13]), hmap2_mobjects[13]), grid[13].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[13])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[19], run_time=0.25))
        self.play(GrowShrink(grid[14], grid[24], run_time=0.25))
        self.play(Write(hmap_mobjects[19]), grid[19].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[19])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[19]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[19], hmap_mobjects[19]), hmap2_mobjects[19]), grid[19].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[19])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[23], run_time=0.25))
        self.play(GrowShrink(grid[22], grid[24], run_time=0.25))
        self.play(Write(hmap_mobjects[23]), grid[23].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[23])), opacity=1), run_time=0.5)
        self.play(Write(hmap_add_mobjects[23]), run_time=0.5)
        self.play(ReplacementTransform(VGroup(hmap_add_mobjects[23], hmap_mobjects[23]), hmap2_mobjects[23]), grid[23].animate.set_fill(color=rgb_to_hex(default_biome_htc(fake_rough_hmap[23])), opacity=1), run_time=0.5)
        self.wait(3)
        self.play(FadeOut(hmap2_mobjects, hmap_mobjects))
        self.wait(3)
        self.play(FadeOut(grid, randomness_tex, r_tex, r_val_tex, r_change_tex))

        self.play(diamond_animation(8))
        self.wait(3)
        self.play(*(mobject.animate.shift(RIGHT * 3.5) for mobject in self.mobjects))
        default_image = ImageMobject("diamond_video/images/default_image.png").scale(0.65).shift(LEFT * 3.5)
        r_value_tex = MathTex("r=0.65").to_edge(DOWN).shift(RIGHT * 3.5)
        self.play(FadeIn(default_image))
        self.wait(3)
        self.play(FadeOut(*self.mobjects))
        self.play(diamond_animation(8, 0.65))
        self.play(*(mobject.animate.shift(RIGHT * 3.5) for mobject in self.mobjects))
        self.wait(2)
        self.play(FadeIn(default_image))
        self.wait(1)
        self.play(Write(r_value_tex))

        self.wait(5)

with tempconfig({"preview": True, "quality": "fourk_quality", "disable_caching": True}):
    scene = CorrectRoughScene()
    scene.render()
