from manim import *
from helper_funcs import *
from diamond_animation import *
from grow_shrink import GrowShrink
from diamond_square import default_biome_htc

class AlgorithmScene(Scene):
    def construct(self):
        self.camera.background_color = DARKER_GRAY

        random_heights = ImageMobject("diamond_video/images/random_heights.png")
        heights_small_img = ImageMobject("diamond_video/images/random_heights_small.png").scale(0.75)
        random_colors2 = ImageMobject("diamond_video/images/random_colors.png").shift(LEFT * 3.5).scale(0.65)
        grid = VGroup(*[Square(side_length=1.425) for i in range(25)])
        grid.arrange_in_grid(rows=5, cols=5, buff=0)
        grid.set_stroke(color=WHITE, width=2)
        grid.set_fill(opacity=0)
        height_map = [
            0.1700, 0.2550, 0.3400, 0.4250, 0.5100,
            0.2800, 1.0313, 0.3313, 0.3494, 0.3138,
            0.3900, 0.3313, 0.3225, 0.3218, 0.2550,
            0.5000, 0.4069, 0.3138, 0.2942, 0.1275,
            0.6100, 0.4575, 0.3050, 0.1525, 0.0000
        ]
        hmap_mobjects = VGroup()
        for index, value in enumerate(height_map):
            mobject = MathTex(f"{value}", color=get_matching_color(default_biome_htc(height_map[index])), z_index=100).move_to(grid[index])
            hmap_mobjects.add(mobject)

        self.wait(1)
        self.play(FadeIn(random_heights))
        self.wait(3)
        self.play(random_heights.animate.shift(RIGHT * 3.5).scale(0.65), FadeIn(random_colors2))
        self.wait(10)
        self.play(random_heights.animate.shift(LEFT * 3.5).scale(1.15), FadeOut(random_colors2))
        self.wait(3)
        self.play(ReplacementTransform(random_heights, heights_small_img), FadeIn(grid))
        self.wait(3)
        self.play(FadeOut(heights_small_img))
        self.wait(3)
        self.play(Write(hmap_mobjects[0]), grid[0].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[0])), opacity=1))
        self.play(Write(hmap_mobjects[4]), grid[4].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[4])), opacity=1))
        self.play(Write(hmap_mobjects[20]), grid[20].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[20])), opacity=1))
        self.play(Write(hmap_mobjects[24]), grid[24].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[24])), opacity=1))
        self.wait(3)
        self.play(GrowShrink(grid[12]))
        self.wait(3)
        self.play(GrowShrink(grid[0], grid[4], grid[20], grid[24]))
        self.wait(3)
        self.play(Write(hmap_mobjects[12]), grid[12].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[12])), opacity=1))
        self.wait(5)
        self.play(GrowShrink(grid[2], grid[10], grid[14], grid[22]))
        self.wait(3)
        self.play(GrowShrink(grid[2]))
        self.wait(3)
        self.play(GrowShrink(grid[0], grid[4]))
        self.wait(3)
        self.play(Write(hmap_mobjects[2]), grid[2].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[2])), opacity=1))
        self.wait(3)
        self.play(GrowShrink(grid[10], grid[14], grid[22]))
        self.wait(3)
        self.play(GrowShrink(grid[14], run_time=0.25))
        self.play(GrowShrink(grid[4], grid[24], run_time=0.25))
        self.play(Write(hmap_mobjects[14]), grid[14].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[14])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[22], run_time=0.25))
        self.play(GrowShrink(grid[20], grid[24], run_time=0.25))
        self.play(Write(hmap_mobjects[22]), grid[22].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[22])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[10], run_time=0.25))
        self.play(GrowShrink(grid[0], grid[20], run_time=0.25))
        self.play(Write(hmap_mobjects[10]), grid[10].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[10])), opacity=1), run_time=0.5)
        self.wait(3)
        self.play(GrowShrink(grid[0], grid[1], grid[2], grid[5], grid[6], grid[7], grid[10], grid[11], grid[12]))
        self.wait(1)
        self.play(GrowShrink(grid[10], grid[11], grid[12], grid[15], grid[16], grid[17], grid[20], grid[21], grid[22]))
        self.wait(1)
        self.play(GrowShrink(grid[2], grid[3], grid[4], grid[7], grid[8], grid[9], grid[12], grid[13], grid[14]))
        self.wait(1)
        self.play(GrowShrink(grid[12], grid[13], grid[14], grid[17], grid[18], grid[19], grid[22], grid[23], grid[24]))
        self.wait(1)
        self.play(GrowShrink(grid[6], run_time=0.25))
        self.play(GrowShrink(grid[0], grid[2], grid[10], grid[12], run_time=0.25))
        self.play(Write(hmap_mobjects[6]), grid[6].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[6])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[16], run_time=0.25))
        self.play(GrowShrink(grid[10], grid[12], grid[20], grid[22], run_time=0.25))
        self.play(Write(hmap_mobjects[16]), grid[16].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[16])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[8], run_time=0.25))
        self.play(GrowShrink(grid[2], grid[4], grid[12], grid[14], run_time=0.25))
        self.play(Write(hmap_mobjects[8]), grid[8].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[8])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[18], run_time=0.25))
        self.play(GrowShrink(grid[12], grid[14], grid[22], grid[24], run_time=0.25))
        self.play(Write(hmap_mobjects[18]), grid[18].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[18])), opacity=1), run_time=0.5)
        self.wait(3)
        self.play(GrowShrink(grid[1], run_time=0.25))
        self.play(GrowShrink(grid[0], grid[2], run_time=0.25))
        self.play(Write(hmap_mobjects[1]), grid[1].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[1])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[7], run_time=0.25))
        self.play(GrowShrink(grid[2], grid[12], run_time=0.25))
        self.play(Write(hmap_mobjects[7]), grid[7].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[7])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[11], run_time=0.25))
        self.play(GrowShrink(grid[10], grid[12], run_time=0.25))
        self.play(Write(hmap_mobjects[11]), grid[11].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[11])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[5], run_time=0.25))
        self.play(GrowShrink(grid[0], grid[10], run_time=0.25))
        self.play(Write(hmap_mobjects[5]), grid[5].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[5])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[17], run_time=0.25))
        self.play(GrowShrink(grid[12], grid[22], run_time=0.25))
        self.play(Write(hmap_mobjects[17]), grid[17].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[17])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[21], run_time=0.25))
        self.play(GrowShrink(grid[20], grid[22], run_time=0.25))
        self.play(Write(hmap_mobjects[21]), grid[21].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[21])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[15], run_time=0.25))
        self.play(GrowShrink(grid[10], grid[20], run_time=0.25))
        self.play(Write(hmap_mobjects[15]), grid[15].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[15])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[3], run_time=0.25))
        self.play(GrowShrink(grid[2], grid[4], run_time=0.25))
        self.play(Write(hmap_mobjects[3]), grid[3].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[3])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[9], run_time=0.25))
        self.play(GrowShrink(grid[4], grid[14], run_time=0.25))
        self.play(Write(hmap_mobjects[9]), grid[9].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[9])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[13], run_time=0.25))
        self.play(GrowShrink(grid[8], grid[18], run_time=0.25))
        self.play(Write(hmap_mobjects[13]), grid[13].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[13])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[19], run_time=0.25))
        self.play(GrowShrink(grid[14], grid[24], run_time=0.25))
        self.play(Write(hmap_mobjects[19]), grid[19].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[19])), opacity=1), run_time=0.5)
        self.play(GrowShrink(grid[23], run_time=0.25))
        self.play(GrowShrink(grid[22], grid[24], run_time=0.25))
        self.play(Write(hmap_mobjects[23]), grid[23].animate.set_fill(color=rgb_to_hex(default_biome_htc(height_map[23])), opacity=1), run_time=0.5)
        self.wait(3)
        self.play(FadeOut(hmap_mobjects))
        self.wait(3)
        self.play(FadeOut(grid))
        self.wait(5)

with tempconfig({"preview": True, "quality": "fourk_quality"}):
    scene = AlgorithmScene()
    scene.render()
